## Generated by Rookframe SDK 0.27.2. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/integration_result.gd"
enum State { UNAVAILABLE, SIGNED_OUT, SIGNED_IN, EXPIRED }
var state: State
func _init(result: Dictionary) -> void:
	super(result)
	state = result.get("state", State.UNAVAILABLE)
