## Generated by Rookframe SDK 0.32.14. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const ActorPortraitResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_portrait_result.gd")
var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
## Host-owned image-file selection. Cancel leaves the Actor untouched.
## Save the returned image bytes through an ordinary Actor update when ready.
func choose() -> ActorPortraitResult:
	var selected: Dictionary = await _scope._complete(_scope._host.ChooseActorPortrait())
	if not selected.get("ok", false):
		return ActorPortraitResult.new(selected)
	return decode(selected.get("data", PackedByteArray()))
func decode(image: PackedByteArray) -> ActorPortraitResult:
	return ActorPortraitResult.new(_scope._host.DecodeActorPortrait(image))
