## Generated by Rookframe SDK 0.32.7. Regenerate with `rookframe facade`.
extends RefCounted
const ExtensionSurface = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/extension_surface.gd")
## System-owned Library presentation. An empty category omits a workflow-only definition.
var category: String
var surface: ExtensionSurface
var can_create: bool
func _init(label: String = "", window: ExtensionSurface = null, creatable: bool = false) -> void:
	category = label
	surface = window
	can_create = creatable
