## Generated by Rookframe SDK 0.32.40. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const ActorPortraitResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_portrait_result.gd")
var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
## Host-owned selection retains the original file in the shared World before success.
## Assign the returned filepath through an ordinary permitted Actor/World update.
## Cancel or acquisition failure leaves the existing Actor reference untouched.
func choose() -> ActorPortraitResult:
	var selected: Dictionary = await _scope._complete(_scope._host.ChooseActorPortrait())
	if not selected.get("ok", false):
		return ActorPortraitResult.new(selected)
	return decode(selected.get("text", ""))
## Local display only; the host resolves the filepath inside this installation's World.
func decode(path: String) -> ActorPortraitResult:
	return ActorPortraitResult.new(_scope._host.DecodeActorPortrait(path))

## Authority saved-data migration only. Retain an existing inline portrait unchanged.
## Return its filepath inside the copied saved value; the host commits the candidate.
func retain(image: PackedByteArray) -> ActorPortraitResult:
	return ActorPortraitResult.new(_scope._host.RetainActorPortrait(image))
