## Generated by Rookframe SDK 0.22.5. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_id.gd")
var id: ActorId
var data: Variant
var access_level: String
var public_label: String
func _init(value: Dictionary) -> void:
	id = ActorId.new(value.id)
	data = value.data
	access_level = value.access_level
	public_label = value.get("public_label", "")
