## Generated by Rookframe SDK 0.27.2. Regenerate with `rookframe facade`.
extends RefCounted
const ActorId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_id.gd")
var actor: ActorId
var data: Variant
func _init(identity: ActorId, replacement: Variant) -> void:
	actor = identity
	data = replacement
func to_record() -> Dictionary:
	return {"id": actor.value, "data": data}
