## Generated by Rookframe SDK 0.32.20. Regenerate with `rookframe facade`.
extends RefCounted
const ContentReference = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/content_reference.gd")

## Presentation-only identity for Rookframe's native Actor list.
var display_name: String
var portrait: Texture2D
var miniature: ContentReference
var can_place: bool
func _init(name: String = "", image: Texture2D = null, model: ContentReference = null, placeable: bool = false) -> void:
	display_name = name
	portrait = image
	miniature = model
	can_place = placeable
