## Generated by Rookframe SDK 0.22.4. Regenerate with `rookframe facade`.
extends Resource
## Matches an admitted authentication.json provider. Contains no confidential credential.
@export var name: String
