## Generated by Rookframe SDK 0.22.2. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const IntegrationResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/integration_result.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func open(url: String) -> IntegrationResult:
	return IntegrationResult.new(await _scope._complete(_scope._host.OpenBrowserLink(url)))
