## Generated by Rookframe SDK 0.28.1. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const IntegrationResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/integration_result.gd")
const TextResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/text_result.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func read_text() -> TextResult:
	return TextResult.new(_scope._host.ReadClipboard())
func write_text(text: String) -> IntegrationResult:
	return IntegrationResult.new(_scope._host.WriteClipboard(text))
