## Generated by Rookframe SDK 0.21.0. Regenerate with `rookframe facade`.
extends RefCounted

const Contribution = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/contribution.gd")
var _host: Object
var _slot: String

func _init(host: Object, slot: String) -> void:
	_host = host
	_slot = slot

## Append an authored contribution in Package-local order. Repeated scenes are idempotent.
func push(entry: Contribution) -> void:
	_host.RegisterContribution(_slot, entry.scene)
