## Generated by Rookframe SDK 0.17.1. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/world_capability.gd")
const ContentReference = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/content_reference.gd")
const ContentEntryResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/content_entry_result.gd")
const ContentEntryListResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/content_entry_list_result.gd")
const ContentKind = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/content_kind.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list(kind: ContentKind.Value = ContentKind.Value.ALL) -> ContentEntryListResult:
	return ContentEntryListResult.new(_host.ListContent(kind))
func read(reference: ContentReference) -> ContentEntryResult:
	return ContentEntryResult.new(_host.ReadContent(reference.package_id, reference.local_id))
