## Generated by Rookframe SDK 0.32.27. Regenerate with `rookframe facade`.
extends RefCounted

const DiceRequest = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/dice_request.gd")
const DiceRollResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/dice_roll_result.gd")
const HumanThrowRequest = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/human_throw_request.gd")
const HumanThrowResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/human_throw_result.gd")
const WorldCapability = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/world_capability.gd")
var _host: Object
func _init(host: Object) -> void:
	_host = host
## Allocate a stable UUID before persisting a requested action.
func new_request_id() -> String:
	return _host.NewHumanThrowRequestId()
## Physically roll now and await the committed raw named result.
func roll(request: DiceRequest) -> DiceRollResult:
	var terms: Array = [] if request == null else request.to_records()
	return DiceRollResult.new(await WorldCapability.new().complete(_host, _host.RollDiceWithId(terms, request.request_id if request != null and not request.request_id.is_empty() else new_request_id())))

const OperationResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/operation_result.gd")

## Stop this Package's local pending Roll and dismiss its dice immediately.
## The awaiting roll returns cancelled. Already accepted Action Log entries stay unchanged.
func cancel_roll(request_id: String) -> OperationResult:
	return OperationResult.new(_host.CancelImmediateRoll(request_id))

## Create or recover one durable request snapshot. This call never remains
## suspended while a human acts; retry request_id after sdk.world_changed.
func request_throw(request: HumanThrowRequest) -> HumanThrowResult:
	if request == null:
		return HumanThrowResult.new(await WorldCapability.new().complete(_host, _host.RequestHumanThrow("", "", [])))
	return HumanThrowResult.new(await WorldCapability.new().complete(_host, _host.RequestHumanThrow(
		request.request_id, request.participant_id, request.to_records())))

## A request that ends when its requester or thrower disconnects. Never resumed.
func request_session_throw(request: HumanThrowRequest) -> HumanThrowResult:
	if request == null:
		return HumanThrowResult.new({"ok": false, "code": "invalid_data", "message": "A request is required."})
	return HumanThrowResult.new(await WorldCapability.new().complete(_host, _host.RequestSessionThrow(
		request.request_id, request.participant_id, request.to_records())))

## Requester or target cancellation. Completed raw Rolls remain unchanged.
func cancel_throw(request_id: String) -> HumanThrowResult:
	return HumanThrowResult.new(await WorldCapability.new().complete(_host, _host.CancelHumanThrow(request_id)))

## Present this Participant's pending request in its owning full-viewport surface.
## The Authority's immutable plan and accepted Roll remain unchanged. Retrying
## the same identity never starts another Roll. Closed surfaces keep running dice.
func roll_requested(request_id: String, source: Control) -> OperationResult:
	return OperationResult.new(_host.PresentRequestedRoll(request_id, source))
