## Generated by Rookframe SDK 0.27.2. Regenerate with `rookframe facade`.
extends Resource

const DiceTerm = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/dice_term.gd")
## Terms retain this order. Their total count may not exceed sixteen dice.
@export var terms: Array[DiceTerm] = []
func _init(requested_terms: Array[DiceTerm] = []) -> void:
	terms = requested_terms
func to_records() -> Array:
	var records: Array = []
	for term in terms:
		records.append({} if term == null else term.to_record())
	return records
