## Generated by Rookframe SDK 0.32.41. Regenerate with `rookframe facade`.
extends Resource

## Authored Control scene hosted by Rookframe's managed window.
## windows.open retains live content across close/reopen.
## windows.open_actor binds one Actor and releases the sheet on close or lost access.
@export var scene: PackedScene
## First-open placement: "left", "right", "floating", or "full-viewport".
## Full-viewport is fixed, has no host title bar, and retains covered windows.
## Its authored task supplies Close; Escape uses the ordinary window lifecycle.
## Other placements remain movable and dockable.
@export var initial_placement := "right"
## Optional first-open dock width in logical pixels. Zero uses Rookframe's responsive default.
@export var initial_dock_width := 0.0
## Optional first-open floating geometry. An empty Rect2 uses Rookframe's responsive default.
@export var initial_floating_rect: Rect2


func initial_presentation() -> Dictionary:
	return {
		"placement": initial_placement,
		"dockWidth": initial_dock_width,
		"floatingRect": initial_floating_rect,
	}
