## Generated by Rookframe SDK 0.16.1. Regenerate with `rookframe facade`.
extends Resource

const FeedbackAction = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/feedback_action.gd")
@export var title: String
@export_multiline var message: String
@export var actions: Array[FeedbackAction] = []
