## Generated by Rookframe SDK 0.16.1. Regenerate with `rookframe facade`.
extends Resource
const FileLocation = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/file_location.gd")

## Portable relative identity in this Package's current areas, never an OS path or grant.
@export var area: FileLocation.Area = FileLocation.Area.USER
@export var name: String
func _init(location: FileLocation.Area = FileLocation.Area.USER, relative_name: String = "") -> void:
	area = location
	name = relative_name
