## Generated by Rookframe SDK 0.25.2. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const ServiceDefinition = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_definition.gd")
const NamedService = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/named_service.gd")
const Account = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/account.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func service(definition: ServiceDefinition, account: Account = null) -> NamedService:
	return NamedService.new(_scope, definition.name, account)
