## Generated by Rookframe SDK 0.25.2. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/setting.gd"
@export var default_value: float = 0.0
@export var minimum: float = -1000000
@export var maximum: float = 1000000
