## Generated by Rookframe SDK 0.17.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/setting.gd"
const Setting = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/setting.gd")
@export var properties: Array[Setting] = []
