## Generated by Rookframe SDK 0.32.30. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/package_sdk_facade.gd")
## Bound automatically before compose().
var sdk: SDK


func compose_presentation(host: Object) -> Control:
	sdk = SDK.new(host)
	compose()
	return self


## Override to register this Presentation's authored UI through the SDK.
func compose() -> void:
	pass


func cleanup_world(completed: Callable) -> void:
	cleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
	operation.complete()


## Optional Presentation-specific form inside Rookframe's settings menu.
@export var settings_view: SDK.SettingsViewDefinition
func _rookframe_settings_view() -> PackedScene:
	return settings_view.scene if settings_view != null else null


## The selected System supplies identity; Rookframe owns listing and access.
func describe_actor(actor: SDK.Actor) -> SDK.ActorSummary:
	return SDK.ActorSummary.new()

## Called when a native Actor row is activated. Open a suitable Actor sheet.
func inspect_actor(actor: SDK.ActorId) -> void:
	pass

func _rookframe_describe_actor(actor_id: String) -> Dictionary:
	var result: SDK.ActorResult = sdk.actors.read(SDK.ActorId.new(actor_id))
	if not result.ok:
		return {}
	var summary: SDK.ActorSummary = describe_actor(result.actor)
	return {"displayName": summary.display_name, "portrait": summary.portrait, "miniature": {"packageId": summary.miniature.package_id, "localId": summary.miniature.local_id} if summary.miniature != null else {}, "canPlace": summary.can_place and result.actor.access_level == "Owner"}

func _rookframe_inspect_actor(actor_id: String) -> void:
	var actor: SDK.ActorId = SDK.ActorId.new(actor_id)
	if sdk.actors.read(actor).ok:
		inspect_actor(actor)


## Place a linked Rook for an existing Actor. Rookframe supplies the drop position.
## Use SDK Rook operations and report a failed placement through sdk.feedback.
func place_actor(actor: SDK.ActorId, scene: SDK.SceneId, position: Vector2) -> void:
	pass

func _rookframe_place_actor(actor_id: String, scene_id: String, position: Vector2) -> void:
	var actor := SDK.ActorId.new(actor_id)
	var result := sdk.actors.read(actor)
	if result.ok and result.actor.access_level == "Owner":
		place_actor(actor, SDK.SceneId.new(scene_id), position)


## Describe reusable Actor Definitions in the host Library; never enumerate live Actors here.
func describe_actor_definition(definition: SDK.ContentEntry) -> SDK.ActorDefinitionView:
	return SDK.ActorDefinitionView.new()

## A Library Create action has no Scene; a tabletop drop supplies Scene and world position.
## Submit ordinary SDK domain operations and present any failure through sdk.feedback.
func create_actor_from_definition(definition: SDK.ContentEntry, scene: SDK.SceneId = null, position: Vector2 = Vector2(0, 0)) -> void:
	pass

func _rookframe_describe_actor_definition(package_id: String, local_id: String) -> Dictionary:
	var result := sdk.content.read(SDK.ContentReference.new(package_id, local_id))
	if not result.ok or result.content_entry.kind != SDK.ContentKind.Value.ACTOR_DEFINITION:
		return {}
	var view := describe_actor_definition(result.content_entry)
	if view == null or view.category.is_empty() or view.surface == null:
		return {}
	return {"category": view.category, "scene": view.surface.scene, "presentation": view.surface.initial_presentation(), "canCreate": view.can_create and result.content_entry.available}

func _rookframe_create_actor_from_definition(package_id: String, local_id: String, scene_id: String, position: Vector2) -> void:
	var result := sdk.content.read(SDK.ContentReference.new(package_id, local_id))
	if result.ok and result.content_entry.available and result.content_entry.kind == SDK.ContentKind.Value.ACTOR_DEFINITION:
		create_actor_from_definition(result.content_entry, SDK.SceneId.new(scene_id) if not scene_id.is_empty() else null, position)
