## Generated by Rookframe SDK 0.28.1. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/world_capability.gd")
const ActorId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_id.gd")
const RookId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/rook_id.gd")
const PublicIdentityResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/public_identity_result.gd")
const PublicIdentityListResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/public_identity_list_result.gd")
const OperationResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list() -> PublicIdentityListResult:
	return PublicIdentityListResult.new(_host.ListPublicIdentities())
func read(rook: RookId) -> PublicIdentityResult:
	return PublicIdentityResult.new(_host.ReadPublicIdentity(rook.value))
func assign(actor: ActorId, label: String) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.SetPublicIdentity(actor.value, label)))
