## Generated by Rookframe SDK 0.25.1. Regenerate with `rookframe facade`.
extends RefCounted

const RookId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/rook_id.gd")
var rook_id: RookId
var label: String
func _init(value: Dictionary) -> void:
	rook_id = RookId.new(value.rookId)
	label = value.label
