## Generated by Rookframe SDK 0.22.5. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/world_capability.gd")
const RookId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/rook_id.gd")
const SceneResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/scene_result.gd")
const DistanceResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/distance_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func current() -> SceneResult:
	return SceneResult.new(_host.CurrentScene())
func distance(from: RookId, to: RookId) -> DistanceResult:
	return DistanceResult.new(_host.RookDistance(from.value, to.value))
