## Generated by Rookframe SDK 0.25.1. Regenerate with `rookframe facade`.
extends RefCounted

const SceneId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/scene_id.gd")
var id: SceneId
var name: String
func _init(value: Dictionary) -> void:
	id = SceneId.new(value.id)
	name = value.name
