## Generated by Rookframe SDK 0.27.2. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const SecretEntry = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/secret_entry.gd")
const SecretSetting = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/secret_setting.gd")

var _scope: ServiceScope
var _area: String
func _init(scope: ServiceScope, area: String) -> void:
	_scope = scope
	_area = area
func entry(name: String) -> SecretEntry:
	return SecretEntry.new(_scope, _area, name)
func setting(descriptor: SecretSetting) -> SecretEntry:
	return entry(descriptor.key)
