## Generated by Rookframe SDK 0.27.2. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/service_scope.gd")
const SecretArea = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/secret_area.gd")

var _user: SecretArea
var _world: SecretArea
var user: SecretArea:
	get:
		return _user
var world: SecretArea:
	get:
		return _world
func _init(scope: ServiceScope) -> void:
	_user = SecretArea.new(scope, "user")
	_world = SecretArea.new(scope, "world")
