## Generated by Rookframe SDK 0.27.2. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/settings_values.gd"
const SettingsScope = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/settings_scope.gd")
var scope: SettingsScope.Kind
func _init(candidate_scope: SettingsScope.Kind, values: Dictionary) -> void:
	super(values)
	scope = candidate_scope
