## Generated by Rookframe SDK 0.21.0. Regenerate with `rookframe facade`.
extends Resource
const Setting = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/setting.gd")
@export var user: Array[Setting] = []
@export var world: Array[Setting] = []
