## Generated by Rookframe SDK 0.16.1. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/world_capability.gd")
const SystemRecordId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/system_record_id.gd")
const SystemRecordResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/system_record_result.gd")
const SystemRecordListResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/system_record_list_result.gd")
const OperationResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list(type_name: String = "") -> SystemRecordListResult:
	return SystemRecordListResult.new(_host.ListSystemRecords(type_name))
func read(id: SystemRecordId) -> SystemRecordResult:
	return SystemRecordResult.new(_host.ReadSystemRecord(id.value))
func create(type_name: String, data: Variant) -> SystemRecordResult:
	return SystemRecordResult.new(await WorldCapability.new().complete(_host, _host.CreateSystemRecord(type_name, data)))
func update(id: SystemRecordId, data: Variant) -> SystemRecordResult:
	return SystemRecordResult.new(await WorldCapability.new().complete(_host, _host.UpdateSystemRecord(id.value, data)))
func delete(id: SystemRecordId) -> OperationResult:
	return OperationResult.new(await WorldCapability.new().complete(_host, _host.DeleteSystemRecord(id.value)))
