## Generated by Rookframe SDK 0.18.1. Regenerate with `rookframe facade`.
extends RefCounted

const SystemRecordId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/system_record_id.gd")
var id: SystemRecordId
var type_name: String
var data: Variant
func _init(value: Dictionary) -> void:
	id = SystemRecordId.new(value.id)
	type_name = value.type_name
	data = value.data
