## Generated by Rookframe SDK 0.22.1. Regenerate with `rookframe facade`.
extends RefCounted
const DataResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/data_result.gd")
const ActorId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_id.gd")
const ActorResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_result.gd")
const RookId = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/rook_id.gd")
const RookResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/rook_result.gd")
const DistanceResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/distance_result.gd")
const ActorAccessListResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_access_list_result.gd")
const HumanThrowRequest = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/human_throw_request.gd")
const HumanThrowResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/human_throw_result.gd")
const ActorChange = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/actor_change.gd")
const ActionLogMessage = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/action_log_message.gd")
const OperationResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/operation_result.gd")
var _host: Object
var _token: String
func _init(host: Object, token: String) -> void:
	_host = host
	_token = token

func new_request_id() -> String:
	return _host.NewHumanThrowRequestId()

## Authenticated requester, session and shared target Rooks. Never client assertions.
func caller() -> DataResult:
	return DataResult.new(_host.SystemIntentContext(_token))
## Complete shared Actor state. access_level describes the requesting Participant.
func read_actor(actor: ActorId) -> ActorResult:
	return ActorResult.new(_host.SystemIntentReadActor(_token, actor.value))
func read_rook(rook: RookId) -> RookResult:
	return RookResult.new(_host.SystemIntentReadRook(_token, rook.value))
func actor_access(actor: ActorId) -> ActorAccessListResult:
	return ActorAccessListResult.new(_host.SystemIntentActorAccess(_token, actor.value))
## Committed logical centers. One tabletop unit is one metre.
func distance(from: RookId, to: RookId) -> DistanceResult:
	return DistanceResult.new(_host.SystemIntentDistance(_token, from.value, to.value))
func read_throw(id: String) -> HumanThrowResult:
	return HumanThrowResult.new(_host.SystemIntentReadThrow(_token, id))
func request_throw(request: HumanThrowRequest) -> HumanThrowResult:
	return HumanThrowResult.new(_host.SystemIntentRequestThrow(_token, request.request_id, request.participant_id, request.to_records()))
func cancel_throw(id: String) -> HumanThrowResult:
	return HumanThrowResult.new(_host.SystemIntentCancelThrow(_token, id))
## Validates every replacement before saving the complete batch. No access grants.
## The System owns rule validation and must deliberately author a public report.
func commit(changes: Array[ActorChange], report: ActionLogMessage = null) -> OperationResult:
	var records: Array = []
	for change in changes:
		records.append(change.to_record())
	return OperationResult.new(_host.SystemIntentCommit(_token, records, report.to_record() if report != null else {}))

## Live Participant sessions, including the GM only when connected.
## Compare exact session identities; reconnect never continues an old action.
func participant_sessions() -> DataResult:
	return DataResult.new(_host.SystemIntentParticipantSessions(_token))
