## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends RefCounted

const WorldCapability = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/world_capability.gd")
const TargetSnapshot = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/target_snapshot.gd")
const TargetSnapshotResult = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/target_snapshot_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host
	_host.TargetingChanged.connect(_changed)

signal changed(snapshot: TargetSnapshot)
func _changed(outcome: Dictionary) -> void:
	changed.emit(TargetSnapshot.new(outcome.value))
func snapshot() -> TargetSnapshotResult:
	return TargetSnapshotResult.new(await WorldCapability.new().complete(_host, _host.TargetingSnapshot()))
