## Generated by Rookframe SDK 0.22.1. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/setting.gd"
@export var default_value: String = ""
@export var choices: PackedStringArray = []
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
