## Generated by Rookframe SDK 0.16.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/setting.gd"
@export var default_value: PackedStringArray = []
@export var minimum_items: int = 0
@export var maximum_items: int = 256
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
