## Generated by Rookframe SDK 0.25.2. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/sdk/package_sdk_facade.gd")
## Bound by Rookframe before the authored window enters the tree. Null in the standalone editor.
var sdk: SDK

func _ready() -> void:
	if has_meta("rookframe_sdk"):
		sdk = SDK.new(get_meta("rookframe_sdk"))
	ready()

## Override for authored view setup; normal Godot child readiness has completed.
func ready() -> void:
	pass

## Explicit closure (including dock replacement), never temporary Dice Tray hiding.
signal closed


## Rookframe delivers the requested Actor on every explicit inspection.
func _rookframe_open_actor(actor_id: String) -> void:
	opened(SDK.ActorId.new(actor_id))

## Query this Actor through sdk.actors.read(actor) and render the returned data.
func opened(actor: SDK.ActorId) -> void:
	pass
