extends GdUnitTestSuite
const ROOT := "res://rookframe/packages/0404eb56-ef27-4b1a-8385-27e4e3ec907e/"
const SDK = preload(ROOT + "sdk/package_sdk_facade.gd")
const SYSTEM = preload(ROOT + "logic/implementation.gd")
const BOUNDARY = preload("res://tests/miniature_boundary.gd")

func _settle() -> void:
	for frame in range(8):
		await get_tree().process_frame

func test_creature_tabs_editing_and_viewer_at_phone_width(width: int, _test_parameters := [[375], [328]]) -> void:
	var host := BOUNDARY.new()
	host.game_master = true
	host.actors.enemy.access_level = "Owner"
	host.actors.enemy.data = preload(ROOT + "content/zukuma-berserker.tres").create_data({})
	host.handler = auto_free(SYSTEM.new())
	host.handler.sdk = SDK.new(host)
	add_child(host.handler)
	var viewport: SubViewport = auto_free(SubViewport.new())
	viewport.size = Vector2i(width, 313)
	viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	add_child(viewport)
	var background: Panel = auto_free(Panel.new())
	background.theme = load("res://rookframe/ui/theme/rookframe_theme.tres")
	background.add_theme_stylebox_override("panel", background.theme.get_stylebox("panel", "RookframePackageInk"))
	viewport.add_child(background)
	background.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	var sheet = auto_free(load(ROOT + "ui/window.tscn").instantiate())
	sheet.sdk = SDK.new(host)
	viewport.add_child(sheet)
	sheet.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	sheet.opened(SDK.ActorId.new("enemy"))
	await _settle()
	var layout: Control = sheet.get_node("Layout")
	assert_bool(layout.position.x >= 12 and layout.get_rect().end.x <= width - 12).override_failure_message("Shared Actor layout must retain both insets after the display safe area reduces the body width.").is_true()
	var tabs: Control = sheet.get_node("Layout/Header/Routes")
	var detail: Control = sheet.get_node("Layout/Body/Content/Detail")
	assert_int(tabs.get_child_count()).is_equal(3)
	assert_bool(detail.get_node("Miniature").is_visible_in_tree()).is_false()
	assert_bool(sheet.get_node("Layout/CreatureEditActions").is_visible_in_tree()).is_false()
	for name in ["Duplicate", "PlaceRook"]:
		assert_bool(sheet.find_child(name, true, false) == null).is_true()
	assert_bool(detail.find_child("CreatureInventory", true, false) == null).is_true()
	var gear: Button = detail.get_node("Identity/EditCreature")
	assert_str(gear.text).is_empty()
	assert_bool(gear.icon != null and gear.size.x == 24 and gear.size.y == 24).is_true()
	assert_bool(sheet.get_global_rect().encloses(gear.get_global_rect())).is_true()
	var attack_rows: Node = detail.get_node("SheetGrid/Left/EquipmentSection/Content/BodySlot/EquipmentList")
	assert_int(attack_rows.get_child_count()).is_equal(4)
	var attack: Button = attack_rows.get_child(0).get_node("Actions/Attack")
	assert_bool(attack.icon != null and not attack.disabled).is_true()
	await _capture(viewport, "%d-creature" % width)
	attack.pressed.emit()
	await _settle()
	assert_bool(sheet.get_node("Layout/Body/Content/CreatureAttack").visible).is_true()
	sheet.get_node("Layout/SheetActions/Back").pressed.emit()
	await _settle()
	gear.pressed.emit()
	await _settle()
	assert_bool(detail.get_node("EditFields").is_visible_in_tree()).is_true()
	var footer: Control = sheet.get_node("Layout/CreatureEditActions")
	assert_bool(footer.is_visible_in_tree()).is_true()
	assert_bool(sheet.get_global_rect().encloses(footer.get_global_rect())).is_true()
	footer.get_node("LeadingSlot/Back").pressed.emit()
	await _settle()
	tabs.get_node("Appearance").pressed.emit()
	await _settle()
	assert_bool(detail.get_node("Miniature").is_visible_in_tree()).is_true()
	assert_bool(detail.get_node("Stats").is_visible_in_tree()).is_false()
	assert_bool(detail.get_node("SheetGrid").is_visible_in_tree()).is_false()
	await _capture(viewport, "%d-appearance" % width)
	tabs.get_node("CreatureInventory").pressed.emit()
	await _settle()
	assert_bool(detail.get_node("Miniature").is_visible_in_tree()).is_false()
	assert_bool(detail.get_node("Inventory").is_visible_in_tree()).is_true()
	await _capture(viewport, "%d-inventory" % width)
	host.actors.enemy.access_level = "Viewer"
	host.WorldChanged.emit()
	await _settle()
	var inventory: Control = detail.get_node("Inventory").get_child(0)
	assert_bool(inventory.get_node("Toolbar/Add").disabled).is_true()
	tabs.get_node("Creature").pressed.emit()
	await _settle()
	assert_bool(gear.is_visible_in_tree()).is_false()

func _capture(viewport: SubViewport, name: String) -> void:
	var directory := OS.get_environment("MORK_SHEET_CAPTURE_DIR")
	if directory.is_empty() or DisplayServer.get_name() == "headless":
		return
	RenderingServer.force_draw()
	DirAccess.make_dir_recursive_absolute(directory)
	assert_int(viewport.get_texture().get_image().save_png(directory.path_join(name + ".png"))).is_equal(OK)

func test_hidden_character_workflow_cannot_replace_creature_chrome() -> void:
	var host := BOUNDARY.new()
	host.game_master = true
	host.actors.enemy.access_level = "Owner"
	host.actors.enemy.data = preload(ROOT + "content/zukuma-berserker.tres").create_data({})
	host.handler = auto_free(SYSTEM.new())
	host.handler.sdk = SDK.new(host)
	add_child(host.handler)
	var sheet = auto_free(load(ROOT + "ui/window.tscn").instantiate())
	sheet.sdk = SDK.new(host)
	add_child(sheet)
	sheet.size = Vector2(326, 315)
	sheet.opened(SDK.ActorId.new("hero"))
	await _settle()
	var character = sheet.find_child("CharacterSheet", true, false)
	character._navigate("rest", "")
	await _settle()
	sheet.opened(SDK.ActorId.new("enemy"))
	await _settle()
	character.workflow_changed.emit("rest", "Action ended", false, false)
	await _settle()
	assert_bool(sheet.get_node("Layout/SheetActions").visible).is_false()
	assert_str(sheet.get_node("Layout/Header/Title").text).is_equal(str(host.actors.enemy.data.name).to_upper())
